version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/app/storage/db.sqlite3
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: "sqlite"
    volumes:
      - ./storage:/data
    command: ["tail", "-f", "/dev/null"] # Mantener el contenedor vivo
volumes:
  storage:
    driver: local
